{ pkgs, ... }:
{
  programs.nix-ld = {
    enable = true;
    libraries = with pkgs; [
      bzip2
      cairo
      dbus
      expat
      fontconfig
      freetype
      gdk-pixbuf
      glib
      glibc
      gnome2.GConf
      gtk2
      gtk3
      lcms2
      libGL
      libICE
      libSM
      libX11
      libXScrnSaver
      libXcomposite
      libXcursor
      libXdamage
      libXext
      libXfixes
      libXi
      libXinerama
      libXrandr
      libXrender
      libXt
      libXtst
      libjpeg
      libpng
      libxcb
      librsvg
      libpulseaudio
      libdrm
      libxkbfile
      libbsd
      mesa
      nspr
      nss
      openssl
      orc
      pango
      pixman
      shared-mime-info
      libxshmfence
      zlib
      SDL2
      libGLU
      libxkbcommon
      icu
      gsettings-desktop-schemas
    ];
  };
}