# To reload when you update config: Run `killall hyprpaper && hyprpaper & disown`
# run `hyprctl monitors all` in order to create your setup.

preload = /home/calielian/Pessoal/tema/wallpaper.png

wallpaper = DP-3,/home/calielian/Pessoal/tema/wallpaper.png

splash = false

wallpaper {
    monitor =
    path = ~/Pessoal/Tema/wallpaper.png
    fit_mode = cover
}
