# Wallpaper setup!
# To reload when you update config: Run `killall hyprpaper` and then `hyperpaper & disown`

# run `hyprctl monitors all` to see all your monitors!!! In order to create your setup.

preload = /home/calielian/Pessoal/tema/wallpaper.png

wallpaper = DP-3,/home/calielian/Pessoal/tema/wallpaper.png

wallpaper {
    monitor =
    path = ~/Pessoal/Tema/wallpaper.png
    fit_mode = cover
}
